"""Initial migration.

Revision ID: 0df0b3cca457
Revises: ccfd593d399b
Create Date: 2024-07-02 11:45:37.849304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df0b3cca457'
down_revision = 'ccfd593d399b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('follow_up', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('appointment', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.add_column('appointment', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('appointment', sa.Column('time', sa.Time(), nullable=False))
    op.add_column('appointment', sa.Column('doctor_id', sa.Integer(), nullable=False))
    op.add_column('appointment', sa.Column('patient_weight', sa.Float(), nullable=True))
    op.add_column('appointment', sa.Column('patient_blood_group', sa.String(length=8), nullable=True))
    op.add_column('appointment', sa.Column('patient_height', sa.Float(), nullable=True))
    op.add_column('appointment', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('appointment', 'reason',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.drop_index('ix_appointment_appointment_time', table_name='appointment')
    op.drop_index('ix_appointment_doctor_name', table_name='appointment')
    op.drop_index('ix_appointment_patient_name', table_name='appointment')
    op.drop_constraint('fk_user_id', 'appointment', type_='foreignkey')
    op.create_foreign_key(None, 'appointment', 'user', ['patient_id'], ['id'])
    op.drop_column('appointment', 'appointment_time')
    op.drop_column('appointment', 'doctor_name')
    op.drop_column('appointment', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('appointment', sa.Column('doctor_name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('appointment', sa.Column('appointment_time', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.create_foreign_key('fk_user_id', 'appointment', 'user', ['user_id'], ['id'])
    op.create_index('ix_appointment_patient_name', 'appointment', ['patient_name'], unique=False)
    op.create_index('ix_appointment_doctor_name', 'appointment', ['doctor_name'], unique=False)
    op.create_index('ix_appointment_appointment_time', 'appointment', ['appointment_time'], unique=False)
    op.alter_column('appointment', 'reason',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('appointment', 'created_at')
    op.drop_column('appointment', 'patient_height')
    op.drop_column('appointment', 'patient_blood_group')
    op.drop_column('appointment', 'patient_weight')
    op.drop_column('appointment', 'doctor_id')
    op.drop_column('appointment', 'time')
    op.drop_column('appointment', 'date')
    op.drop_column('appointment', 'patient_id')
    op.drop_table('queue')
    op.drop_table('prescription')
    op.drop_table('billing')
    # ### end Alembic commands ###
