"""empty message

Revision ID: 8676462f2d0d
Revises: 
Create Date: 2025-04-19 17:21:50.225011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8676462f2d0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=255), nullable=False),
    sa.Column('patient_blood_group', sa.String(length=3), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('currentdate', sa.DateTime(), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_table('patientpass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('patient_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['patient.email'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('patientvisit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('appointment_id', sa.String(length=64), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('blood_pressure_high', sa.Integer(), nullable=False),
    sa.Column('blood_pressure_low', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('medical_condition', sa.String(length=255), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_table('doctordetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('doctor_notes', sa.Text(), nullable=False),
    sa.Column('doctor_name', sa.String(length=50), nullable=False),
    sa.Column('medications', sa.Text(), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['patientvisit.appointment_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.ForeignKeyConstraint(['visit_date'], ['patientvisit.visit_date'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['patientvisit.appointment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue')
    op.drop_table('doctordetails')
    op.drop_table('patientvisit')
    op.drop_table('patientpass')
    op.drop_table('billing')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('patient')
    # ### end Alembic commands ###
